### ISSUE TITLE
Throttle Google Requests

### ISSUE THREAD

**Issue by dsumorok-raytheon** [SD2E/sbol-dictionary-maintainer#26]
The throttling of Google requests does not appear to be working properly, as the dictionary is exceeding the quota for requests in a 100 second period.  All Google requests should now eventually get called from the same "execute" method in the Dictionary Accessor.  Perhaps the throttling should be done there, instead of throughout the code like it is done now.

**Comment by jakebeal** [comment]
Fixed by #27
