### ISSUE TITLE
Protection Errors

### ISSUE THREAD

**Issue by rkrishnasanka** [SD2E/sbol-dictionary-maintainer#28]
Please check the attached file for the errors, from what we could see, the software is running but something is broken inside of it.

[dictionary_log.log](https://github.com/SD2E/sbol-dictionary-maintainer/files/3376880/dictionary_log.log)

**Comment by jakebeal** [comment]
It looks like the sheet wasn't shared with the lcpdictionary user.  I've shared it now. Can you please try running again?

**Comment by jakebeal** [comment]
This has now been sorted out, appearing to have been configuration issues.
