### ISSUE TITLE
Add a column for Salis Lab

### ISSUE THREAD

**Issue by mwes** [SD2E/sbol-dictionary-maintainer#31]
Please add a column for the Salis Lab at Penn State to the SD2 Program Dictionary. We internally will be using PennState_Salis (e.g. in the samples JSON Schema to go along with the other institution_lab identifiers). For purposes of the dictionary, I recommend "PennState (Salis) UID" as the column header.

**Comment by mwes** [comment]
Last done for CalTech, e.g. https://github.com/SD2E/sbol-dictionary-maintainer/pull/16

**Comment by mwes** [comment]
Email contacts: Howard Salis, salis@psu.edu, Jacob Beal, Mark Weston

**Comment by dsumorok-raytheon** [comment]
A new dictionary version has been deployed and is ready for testing.

**Comment by jakebeal** [comment]
@mwes When you're satisfied, please close this issue.

**Comment by mwes** [comment]
Sorry - didn't get this notification. Confirm the new column is in place, thanks.
