### ISSUE TITLE
Dictionary appears to be not be updating

### ISSUE THREAD

**Issue by mwes** [SD2E/sbol-dictionary-maintainer#34]
https://docs.google.com/spreadsheets/d/1oLJTTydL_5YPyk-wY-dspjIw_bPZ3oCiWiK0xtG8t3g

The Google Sheets program dictionary appears to not be updating - see entry for beta estradiol

![image](https://user-images.githubusercontent.com/5033275/68032466-fa79b280-fc7a-11e9-8d88-a6397488b9f4.png)

**Comment by mwes** [comment]
FYSA: @jakebeal

**Comment by jakebeal** [comment]
Can you check the docker on TACC and see if it is still alive?

**Comment by mwes** [comment]
It's running, but appears to be hitting some kind of error that is likely preventing the beta estradiol row from being processed:
![image](https://user-images.githubusercontent.com/5033275/68127616-36fc1700-fee4-11e9-95d6-c3e840d3459c.png)

**Comment by jakebeal** [comment]
I'm going to try to borrow @dsumorok-raytheon for a couple of hours to help sort this out.

**Comment by jakebeal** [comment]
@dsumorok-raytheon is planning to address this on Friday.

**Comment by mwes** [comment]
This appears to be fixed in the latest run. Thanks!

![image](https://user-images.githubusercontent.com/5033275/68887779-97ab0100-06e7-11ea-8eb0-1595e7a2ad0a.png)
