### ISSUE TITLE
Add a column for Straeos-XPlan

### ISSUE THREAD

**Issue by mwes** [SD2E/sbol-dictionary-maintainer#46]
Strateos requires a target _input_ schema that is different from its _output_ schema when reporting against, for example, media. 

To resolve this, we'll need to add a dictionary column that allows us to target this Strateos input, passed through from XPlan.

Please add a column to the Program Dictionary for this. For the purposes of the dictionary, I recommend something like "Strateos-XPlan" as the column header.

**Comment by jakebeal** [comment]
Is there any reason that we need to have two columns for this? Why not have just put both items in the one column?

**Comment by mwes** [comment]
Ah - we need to be able to unambiguously reverse the mapping. Given an entry in the request using the Common Name/URI ("Modified M9 Media/https://hub.sd2e.org/user/sd2e/design/Modified0x20M90x20Media/1"), XPlan needs to convert this into the Strateos input term ("modified_m9_media"), which is different from the output term they provide in their lab trace ("rs1dqz79wyjubwn"). If the mappings independent, we can do this. If they're combined, the result is ambiguous. There may be another way, happy to discuss.

**Comment by jakebeal** [comment]
I see: the problem is that Strateos doesn't actually provide this term.  We can add a column, but I'm very uncomfortable with this because it feels like opening of a problematic kludge... can we get a meeting with Dan & Josh to try to sort this out?

**Comment by mwes** [comment]
Certainly, we are discussing on #ip-sr-xplan

**Comment by jakebeal** [comment]
Alternative approach agreed via Slack discussion: Strateos will just use their internal IDs.

**Comment by jakebeal** [comment]
@joshtx will handle this
