### ISSUE TITLE
Add columns for Duke Haase Lab and TACC

### ISSUE THREAD

**Issue by mwes** [SD2E/sbol-dictionary-maintainer#47]
Please add two columns to the dictionary:

1. A column for the Haase Lab at Duke. They are running experiments now, and have strain ids we need to map to SD2 Strain URIs and Common names.

2. A column for TACC. The intent-parser has requested that a set of TA4 infrastructure terms be translated into more amenable/user-facing terms. We can use the dictionary to do this, but need a non lab-centric way of doing this (these terms are universal across all labs). My suggestion is to add a column for TACC, which will allow us to translate these terms. See: 

https://docs.google.com/document/d/1GJydNCNmiTTyf8m5LjBfEhMblLvaCincK8SBwbsg1t4/ 

for additional context.

@jakebeal I am not sure who on your team will work this. I am assigning to you initially in the hope that you will be able to delegate and re-assign as needed.

**Comment by jakebeal** [comment]
New columns are in the sheet, and I've set up a pull request for @eriksf to pull to the container and reboot.

https://gitlab.sd2e.org/sd2program/sd2-dictionary-build/merge_requests/2

I am now reassigning to @eriksf , who needs to execute the next step here.

**Comment by eriksf** [comment]
Container (v1.0.2) pulled and rebooted on https://admin.services-ec2-04.sd2e.org/ and running happily. Please verify.

**Comment by jakebeal** [comment]
Success validated. Thank you!
