### ISSUE TITLE
Allow aliases of common name

### ISSUE THREAD

**Issue by jakebeal** [SD2E/sbol-dictionary-maintainer#9]
(migrated and adapted from old GitLab repository)

The dictionary should have another column that allows alternate names for aliases for the common name, where the common name is the preferred variant.

**Comment by jakebeal** [comment]
Need to talk with Chris Myers about aliases to decide where to put it in SBOL.

**Comment by jakebeal** [comment]
Looks to me like the right thing to use here is `dcterms:alternative`. 

The common name is specified as a "name" attribute, which is designated with the standard class `dcterms:title`. As it turns out, alternative titles is already a well thought out idea in Dublin Core, and `dcterms:alternative` is available as a subclass of `dcterms:title`: http://dublincore.org/specifications/dublin-core/dcmi-terms/2012-06-14/?v=terms#alternative

**Comment by jakebeal** [comment]
Some things have commas in their names, so we will want to use semicolons as the dividers if one has more than one alternate name.

**Comment by jakebeal** [comment]
Chris Myers says that SynBioHub should show these in the "Other Properties" section at the moment, which is fine.

**Comment by tramyn** [comment]
@jakebeal is there a list of alias terms stored somewhere?

**Comment by tramyn** [comment]
Oh I think I understand what you are suggesting now. In this issue, you are requesting that the dictionary support common name represented in SBOL as dcterms:title and dcterms:alternative as a list of alias terms. Is this correct @jakebeal ?

**Comment by jakebeal** [comment]
Yes, that's right.
